- name: Manage all EC2 instances
  hosts: all
  become: true
  tasks:

    - name: Update and upgrade apt packages (Ubuntu only)
      apt:
        update_cache: yes
        upgrade: dist
      when: ansible_os_family == "Debian"

#    - name: Update and upgrade dnf packages (Amazon Linux 2023 or RedHat)
#      ansible.builtin.command: dnf upgrade -y
#      when: ansible_distribution in ["Amazon", "RedHat"]

    - name: Install Docker if not present
      package:
        name: docker
        state: present

    - name: Start and enable Docker
      service:
        name: docker
        state: started
        enabled: yes

    - name: Check Docker version
      command: docker --version
      register: docker_version_output
      changed_when: false

    - name: Print Docker version
      debug:
        msg: "{{ docker_version_output.stdout }}"

    - name: Report disk usage
      command: df -h
      register: disk_usage

    - name: Print disk usage
      debug:
        var: disk_usage.stdout_lines
